dist: bionic

language: cpp

addons:
  apt:
    packages:
    - build-essential
    - bison
    - libevent-dev
    - libmysqlclient-dev
    - libpcre3-dev
    - libpq-dev
    - libsqlite3-dev
    - libz-dev
    - libgtest-dev

script: ./build.FluffOS && make

compiler:
  - clang
